//
//  WelcomePresenter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomePresentationLogic {
    func dataReceived()
    func error(_ type: ErrorType)
}

final class WelcomePresenter: WelcomePresentationLogic {
    weak var viewController: WelcomeDisplayLogic?
    
    func dataReceived() {
        DispatchQueue.main.async {
            self.viewController?.requirementsCompleted()
        }
    }
    
    func error(_ type: ErrorType) {
        switch type {
        case .network:
            let alert = AlertModel(title: "alert_title_error", description: "alert_description_network")
            DispatchQueue.main.async {
                self.viewController?.displayAlert(alert)
            }
        case .undefined:
            let alert = AlertModel(title: "alert_title_error", description: "alert_description_genericError")
            DispatchQueue.main.async {
                self.viewController?.displayAlert(alert)
            }
        }
    }
}
