//
//  WelcomeRouter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic {
    func navigateToProductManagement()
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

class WelcomeRouter: NSObject, WelcomeRoutingLogic, WelcomeDataPassing {
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?
    
    func navigateToProductManagement() {
        guard let navigationController = UIStoryboard(name: "ProductManagement", bundle: nil).instantiateInitialViewController() as? UINavigationController, let productSelectionViewController = navigationController.viewControllers.first as? ProductSelectionViewController else {
            return
        }
        
        var productSelectionViewControllerDS = productSelectionViewController.router!.dataStore!
        passDataToProductSelection(source: dataStore!, destination: &productSelectionViewControllerDS)
        UIApplication.shared.windows.first?.rootViewController = productSelectionViewController
    }
    
    private func passDataToProductSelection(source: WelcomeDataStore, destination: inout ProductSelectionDataStore) {
        destination.rates = source.rates
        destination.transactions = source.transactions
    }
}
