//
//  WelcomeViewController.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: class {
    func displayAlert(_ alert: AlertModel)
    func requirementsCompleted()
}

final class WelcomeViewController: UIViewController {
    @IBOutlet private weak var loadingHUD: UIActivityIndicatorView!
    @IBOutlet private weak var retryButton: UIButton!
    
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        let viewController = self
        let interactor = WelcomeInteractor()
        let presenter = WelcomePresenter()
        let router = WelcomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupButton()
    }
    
    private func setupButton() {
        retryButton.setTitle("welcome_retry".localized, for: .normal)
        retryButton.layer.cornerRadius = 4
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        requestData()
    }
    
    @IBAction private func retryTouchUp() {
        requestData()
    }
    
    func requestData() {
        loadingHUD.startAnimating()
        interactor?.requestData()
    }
}

extension WelcomeViewController: WelcomeDisplayLogic {
    func displayAlert(_ alert: AlertModel) {
        loadingHUD.stopAnimating()
        retryButton.isHidden = false
        AlertManager.displayAlert(alert, source: self)
    }
    
    func requirementsCompleted() {
        loadingHUD.stopAnimating()
        print("jobs done")
    }
}
