//
//  WelcomeInteractor.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic {
    func requestData()
}

protocol WelcomeDataStore {
    var rates: [RateModel] { get set }
    var transactions: [TransactionModel] { get set }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore {
    var presenter: WelcomePresentationLogic?
    var rates = [RateModel]()
    var transactions = [TransactionModel]()
    
    func requestData() {
        if rates.isEmpty {
            requestRates()
        } else if transactions.isEmpty {
            requestTransactions()
        } else {
            presenter?.dataReceived()
        }
    }
    
    private func requestRates() {
        APIClient.requestCurrencyRates { (response) in
            switch response {
            case .success(let rates):
                self.rates = rates
                self.requestData()
            case .error(let error):
                self.presenter?.error(error)
            }
        }
    }
    
    private func requestTransactions() {
        APIClient.requestTransactions { (response) in
            switch response {
            case .success(let transactions):
                self.transactions = transactions
                self.requestData()
            case .error(let error):
                self.presenter?.error(error)
            }
        }
    }
}
