//
//  WelcomeInteractor.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic {
    func requestData()
}

protocol WelcomeDataStore {
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore {
    var presenter: WelcomePresentationLogic?
    var rates = [RateModel]()
    
    func requestData() {
        if rates.isEmpty {
            requestRates()
        } else {
            presenter?.dataReceived()
        }
    }
    
    private func requestRates() {
        APIClient.requestCurrencyRates { (response) in
            switch response {
            case .success(let rates):
                self.rates = rates
                self.requestData()
            case .error(let error):
                self.presenter?.error(error)
            }
        }
    }
}
