//
//  ProductSelectionRouter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductSelectionRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ProductSelectionDataPassing {
    var dataStore: ProductSelectionDataStore? { get }
}

class ProductSelectionRouter: NSObject, ProductSelectionRoutingLogic, ProductSelectionDataPassing {
    weak var viewController: ProductSelectionViewController?
    var dataStore: ProductSelectionDataStore?
    
//    // MARK: Routing
//    
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
//    
//    //     MARK: Navigation
//    
//    func navigateToSomewhere(source: ProductSelectionViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
//    
//    //     MARK: Passing data
//    
//    func passDataToSomewhere(source: ProductSelectionDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
