//
//  ProductSelectionInteractor.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductSelectionBusinessLogic {
}

protocol ProductSelectionDataStore {
    var rates: [RateModel] { get set }
    var transactions: [TransactionModel] { get set }
}

class ProductSelectionInteractor: ProductSelectionBusinessLogic, ProductSelectionDataStore {
    var rates = [RateModel]()
    var transactions = [TransactionModel]()
    var presenter: ProductSelectionPresentationLogic?
}
