//
//  ProductOverviewViewController.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductOverviewDisplayLogic: class {
    func displayProductId(_ id: String)
    func displayTransactions(_ transactions: [TransactionModel])
    func displayTotalValue(_ value: Double)
    func displayCurrencies(_ currencies: [String])
}

final class ProductOverviewViewController: UIViewController {
    @IBOutlet private weak var transactionsTableView: UITableView!
    @IBOutlet private weak var totalValueLabel: UILabel!
    @IBOutlet private weak var currenciesPickerView: UIPickerView!
    @IBOutlet private var currenciesPickerViewHidingConstraint: NSLayoutConstraint!
    @IBOutlet private weak var changeCurrencyButton: UIButton!
    
    private var transactions = [TransactionModel]() {
        didSet {
            view.layoutIfNeeded()
            transactionsTableView.reloadData()
        }
    }
    private var currencies = [String]() {
        didSet {
            currenciesPickerView.reloadAllComponents()
            if let row = currencies.firstIndex(of: currentCurrency) {
                currenciesPickerView.selectRow(row, inComponent: 0, animated: false)
                pickerView(currenciesPickerView, didSelectRow: row, inComponent: 0)
            }
        }
    }
    private var currentCurrency = Constants.ProductOverview.defaultCurrency {
        didSet {
            changeCurrencyButton.setTitle(currentCurrency, for: .normal)
            totalValueLabel.text = "productOverview_total_placeholder".localized
            interactor?.calculateTotalValue(forCurrency: currentCurrency)
        }
    }
    
    var interactor: ProductOverviewBusinessLogic?
    var router: (NSObjectProtocol & ProductOverviewRoutingLogic & ProductOverviewDataPassing)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        let viewController = self
        let interactor = ProductOverviewInteractor()
        let presenter = ProductOverviewPresenter()
        let router = ProductOverviewRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        transactionsTableView.register(TransactionTableViewCell.nib(), forCellReuseIdentifier: TransactionTableViewCell.nibName())
        changeCurrencyButton.setTitle("productOverview_currency_changeButton".localized, for: .normal)
        currenciesPickerView.reloadAllComponents()
        interactor?.getData()
    }
    
    @IBAction func changeCurrencyTouchUp() {
        UIView.animate(withDuration: 0.3) {
            self.currenciesPickerViewHidingConstraint.isActive = false
            self.view.layoutIfNeeded()
        }
    }
}

extension ProductOverviewViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return transactions.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: TransactionTableViewCell.nibName()) as? TransactionTableViewCell else {
            return UITableViewCell()
        }
        
        cell.setup(TransactionTableViewCellModel(amount: transactions[indexPath.row].amount, currency: transactions[indexPath.row].currency))
        
        return cell
    }
}

extension ProductOverviewViewController: UIPickerViewDataSource {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return currencies.count
    }
}

extension ProductOverviewViewController: UIPickerViewDelegate {
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return currencies[row]
    }
    
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        currentCurrency = currencies[row]
        UIView.animate(withDuration: 0.3) {
            self.currenciesPickerViewHidingConstraint.isActive = true
            self.view.layoutIfNeeded()
        }
    }
}

extension ProductOverviewViewController: ProductOverviewDisplayLogic {
    func displayProductId(_ id: String) {
        title = "productOverview_title".localized + ": " + id
    }
    
    func displayTransactions(_ transactions: [TransactionModel]) {
        self.transactions = transactions
    }
    
    func displayTotalValue(_ value: Double) {
        totalValueLabel.text = String(format: "productOverview_total".localized, value)
    }
    
    func displayCurrencies(_ currencies: [String]) {
        self.currencies = currencies
    }
}
