//
//  ProductOverviewRouter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductOverviewRoutingLogic {
}

protocol ProductOverviewDataPassing {
    var dataStore: ProductOverviewDataStore? { get }
}

class ProductOverviewRouter: NSObject, ProductOverviewRoutingLogic, ProductOverviewDataPassing {
    weak var viewController: ProductOverviewViewController?
    var dataStore: ProductOverviewDataStore?
}
