//
//  ProductOverviewPresenter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductOverviewPresentationLogic {
    func presentProductId(_ id: String)
    func presentTransactions(_ transactions: [TransactionModel])
    func presentTotal(_ values: [Double])
}

final class ProductOverviewPresenter: ProductOverviewPresentationLogic {
    weak var viewController: ProductOverviewDisplayLogic?
    
    func presentProductId(_ id: String) {
        viewController?.displayProductId(id)
    }
    
    func presentTransactions(_ transactions: [TransactionModel]) {
        viewController?.displayTransactions(transactions)
    }
    
    func presentTotal(_ values: [Double]) {
        var totalValue: Double = 0
        values.forEach({ totalValue += $0 })
        viewController?.displayTotalValue(totalValue)
    }
}
