//
//  ProductOverviewInteractor.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductOverviewBusinessLogic {
    func getData()
}

protocol ProductOverviewDataStore {
    var rates: [RateModel] { get set }
    var transactions: [TransactionModel] { get set }
}

class ProductOverviewInteractor: ProductOverviewBusinessLogic, ProductOverviewDataStore {
    var rates = [RateModel]()
    var transactions = [TransactionModel]()
    var convertedTransactionsValue = [Int: Double]() {
        didSet {
            if convertedTransactionsValue.count == transactions.count {
                presenter?.presentTotal([Double](convertedTransactionsValue.values))
            }
        }
    }
    
    var presenter: ProductOverviewPresentationLogic?
    
    func getData() {
        let productId = transactions.first?.sku ?? ""
        presenter?.presentProductId(productId)
        presenter?.presentTransactions(transactions)
        manageTotalTransaction()
    }
    
    func manageTotalTransaction() {
        convertedTransactionsValue = [Int: Double]()
        
        transactions.enumerated().forEach { (position, transaction) in
            RateUtils().convertTo("EUR", amount: transaction.amount, currency: transaction.currency, rates: rates, completion: { (rate) in
                let value = (Double(transaction.amount) ?? 0) * rate
                if value != 0 {
                    self.convertedTransactionsValue[position] = value
                }
            })
        }
    }
}
