//
//  ProductSelectionPresenter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductSelectionPresentationLogic {
    func filteredProducts(_ products: [String])
    func productSelected()
}

final class ProductSelectionPresenter: ProductSelectionPresentationLogic {
    weak var viewController: ProductSelectionDisplayLogic?
    
    func filteredProducts(_ products: [String]) {
        viewController?.displayProducts(products)
    }
    
    func productSelected() {
        viewController?.goToProduct()
    }
}
