//
//  ProductSelectionViewController.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductSelectionDisplayLogic: class {
    func displayProducts(_ products: [String])
    func goToProduct()
}

final class ProductSelectionViewController: UIViewController {
    @IBOutlet private weak var filterTextField: UITextField!
    @IBOutlet private weak var productsTableView: UITableView!
    
    var interactor: ProductSelectionBusinessLogic?
    var router: (NSObjectProtocol & ProductSelectionRoutingLogic & ProductSelectionDataPassing)?
    
    var products = [String]() {
        didSet {
            currentFilter = ""
            filteredProducts = products
        }
    }
    
    var currentFilter = ""
    var filteredProducts = [String]() {
        didSet {
            productsTableView.reloadData()
        }
    }
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        let viewController = self
        let interactor = ProductSelectionInteractor()
        let presenter = ProductSelectionPresenter()
        let router = ProductSelectionRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        productsTableView.register(ProductSelectionTableViewCell.nib(), forCellReuseIdentifier: ProductSelectionTableViewCell.nibName())
        interactor?.getData()
    }
    
    @IBAction func filterValueChanged() {
        let currentText = filterTextField.text ?? ""
        
        if currentText.count == 0 {
            filteredProducts = products
        } else if currentFilter.count < currentText.count {
            filterProducts(currentText, newFilter: false)
        } else {
            filterProducts(currentText, newFilter: true)
        }
        
        currentFilter = currentText
    }
    
    private func filterProducts(_ filter: String, newFilter: Bool) {
        if newFilter {
            filteredProducts = products.filter({$0.lowercased().contains(filter.lowercased())})
        } else {
            filteredProducts = filteredProducts.filter({$0.lowercased().contains(filter.lowercased())})
        }
    }
}

extension ProductSelectionViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return filteredProducts.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: ProductSelectionTableViewCell.nibName()) as? ProductSelectionTableViewCell else {
            return UITableViewCell()
        }
        
        cell.setup(ProductSelectionTableViewCellModel(productName: filteredProducts[indexPath.row]))
        
        return cell
    }
}

extension ProductSelectionViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        guard let productTableViewCell = tableView.cellForRow(at: indexPath) as? ProductSelectionTableViewCell else {
            return
        }
        
        interactor?.selectedProduct(productTableViewCell.model?.productName ?? "")
    }
}

extension ProductSelectionViewController: UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.endEditing(true)
        return false
    }
    
}

extension ProductSelectionViewController: ProductSelectionDisplayLogic {
    func displayProducts(_ products: [String]) {
        self.products = products
    }
    
    func goToProduct() {
        router?.navigateToProduct()
    }
}
