//
//  ProductSelectionRouter.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductSelectionRoutingLogic {
    func navigateToProduct()
}

protocol ProductSelectionDataPassing {
    var dataStore: ProductSelectionDataStore? { get }
}

class ProductSelectionRouter: NSObject, ProductSelectionRoutingLogic, ProductSelectionDataPassing {
    weak var viewController: ProductSelectionViewController?
    var dataStore: ProductSelectionDataStore?
    
    func navigateToProduct() {
        guard let productOverviewViewController = UIStoryboard(name: "ProductManagement", bundle: nil).instantiateViewController(withIdentifier: "ProductOverviewViewController") as? ProductOverviewViewController else {
            return
        }
        
        var productOverviewViewControllerDS = productOverviewViewController.router!.dataStore!
        passDataToProductOverview(source: dataStore!, destination: &productOverviewViewControllerDS)
        viewController?.navigationController?.pushViewController(productOverviewViewController, animated: true)
    }
    
    private func passDataToProductOverview(source: ProductSelectionDataStore, destination: inout ProductOverviewDataStore) {
        destination.rates = source.rates
        destination.transactions = source.selectedProductTransactions
    }
}
