//
//  ProductSelectionInteractor.swift
//  BemobileGNB
//
//  Created by Admin on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductSelectionBusinessLogic {
    func getData()
    func selectedProduct(_ productSKU: String)
}

protocol ProductSelectionDataStore {
    var rates: [RateModel] { get set }
    var transactions: [TransactionModel] { get set }
    var selectedProductTransactions: [TransactionModel] { get set }
}

class ProductSelectionInteractor: ProductSelectionBusinessLogic, ProductSelectionDataStore {
    var rates = [RateModel]()
    var transactions = [TransactionModel]()
    var selectedProductTransactions = [TransactionModel]()
    
    var presenter: ProductSelectionPresentationLogic?
    
    func getData() {
        var products = [String]()
        
        transactions.forEach { (transaction) in
            if !products.contains(transaction.sku) {
                products.append(transaction.sku)
            }
        }
        
        presenter?.filteredProducts(products)
    }
    
    func selectedProduct(_ productSKU: String) {
        selectedProductTransactions = transactions.filter({$0.sku == productSKU})
        presenter?.productSelected()
    }
}
